## YAML Template
---
# password
password: p@ssw0rd

server:
    applicationConnectors:
        - type: http
          port: 8085
        - type: https
          port: 8443
          keyStorePath: digitaleFactuurBackEnd.keystore
          keyStorePassword: p@ssw0rd
          validateCerts: false

database:
    driverClass: org.postgresql.Driver
    user: postgres
    password: 1234
    url: jdbc:postgresql://localhost/iipsen
